### ISSUE TITLE
RotatedMNIST doesn't work with torchvision 0.8.2 ('torchvision.transforms' has no attribute 'InterpolationMode')

### ISSUE THREAD

**Issue by josh-gleason** [facebookresearch/DomainBed#122]
Running `train.py` with `--dataset RotatedMNIST` causes an exception when using torchvision 0.8.2, which is the version currently specified in [domainbed/requirements.txt](https://github.com/facebookresearch/DomainBed/blob/3ab2b63e4e270686cd45c8ea7444c4418c0d77bc/domainbed/requirements.txt).

The problem is that the call to [`torchvision.transforms.functional.rotate`](https://pytorch.org/vision/0.8/transforms.html#torchvision.transforms.functional.rotate) was changed in commit 27e115e66 from https://github.com/facebookresearch/DomainBed/blob/4f4e6a7fec7ed81f93a5d218962480498503e0dd/domainbed/datasets.py#L170 to https://github.com/facebookresearch/DomainBed/blob/27e115e66bb84412db7017874bd8ee446d057610/domainbed/datasets.py#L167

But the `interpolation` argument for `rotate` was not added until torchvision 0.9.

It's also worth pointing out that the semantics here have actually changed as well since the interpolation mode was changed from BICUBIC to BILINEAR, which may have an impact on results. A change that impacts the results of the benchmark seems like something that should be avoided.

**Comment by lopezpaz** [comment]
We didn't observe any changes at the time, but please feel free to reopen if you do. We should update `requirements.txt` anyway.
